export const physicalTypes = [
   "armor",
   "weapon",
   "shield",
   "equipment",
   "consumable",
   "treasure",
   "backpack",
]

export const materialStats = {
   paper: {
      hd: 0,
      hp: 1,
   },
   "cloth-thin": {
      hd: 0,
      hp: 1,
   },
   "glass-thin": {
      hd: 0,
      hp: 1,
   },
   cloth: {
      hd: 1,
      hp: 4,
   },
   glass: {
      hd: 1,
      hp: 4,
   },
   "glass-structure": {
      hd: 2,
      hp: 8,
   },
   "leather-thin": {
      hd: 2,
      hp: 8,
   },
   "rope-thin": {
      hd: 2,
      hp: 8,
   },
   "wood-thin": {
      hd: 3,
      hp: 12,
   },
   leather: {
      hd: 4,
      hp: 16,
   },
   rope: {
      hd: 4,
      hp: 16,
   },
   "stone-thin": {
      hd: 5,
      hp: 16,
   },
   "iron-thin": {
      hd: 5,
      hp: 20,
   },
   wood: {
      hd: 5,
      hp: 20,
   },
   stone: {
      hd: 7,
      hp: 28,
   },
   iron: {
      hd: 9,
      hp: 36,
   },
   "wood-structure": {
      hd: 10,
      hp: 40,
   },
   "stone-structure": {
      hd: 14,
      hp: 56,
   },
   "iron-structure": {
      hd: 18,
      hp: 72,
   },
}

export const armorPropertyMap = {
   acidResistant: {
      type: "resistance",
      element: "acid",
      value: -5,
   },
   coldResistant: {
      type: "resistance",
      element: "cold",
      value: -5,
   },
   electricityResistant: {
      type: "resistance",
      element: "electricity",
      value: -5,
   },
   fireResistant: {
      type: "resistance",
      element: "fire",
      value: -5,
   },
   sonicResistant: {
      type: "resistance",
      element: "sonic",
      value: -5,
   },
   shadow: {
      type: "skill",
      skill: "stealth",
      value: -1,
   },
   greaterShadow: {
      type: "skill",
      skill: "stealth",
      value: -2,
   },
   majorShadow: {
      type: "skill",
      skill: "stealth",
      value: -3,
   },
   slick: {
      type: "skill",
      skill: "acrobatics",
      value: -1,
   },
   greaterSlick: {
      type: "skill",
      skill: "acrobatics",
      value: -2,
   },
   majorSlick: {
      type: "skill",
      skill: "acrobatics",
      value: -3,
   },
}

export const weaponPropertyMap = {
   flaming: { element: "fire" },
   frost: { element: "cold" },
   shock: { element: "electricity" },
   corrosive: { element: "acid" },
   thundering: { element: "sonic" },
   holy: { element: "spirit" },
   unholy: { element: "spirit" },
}

export const baseArmorMaterials = {
   paper: ["Scroll Robes"],
   cloth: ["explorers-clothing", "padded-armor", "quilted-armor", "Gi"],
   "wood-thin": ["Rattan Armor"],
   leather: [
      "leather-armor",
      "studded-leather-armor",
      "hide-armor",
      "Armored Coat",
      "Leaf Weave",
      "Leather Lamellar",
      "Armored Cloak",
   ],
   wood: [
      "wooden-breastplate",
      "Buckle Armor",
      "Sankeit",
      "chain-shirt",
      "Niyaháat",
   ],
   stone: [
      "Ceramic Plate",
      "Coral Armor",
      "Mantis Shell",
      "chain-mail",
      "Lamellar Breastplate",
   ],
   iron: [
      "breastplate",
      "Hellknight Breastplate",
      "O-Yoroi",
      "Kilted Breastplate",
      "Scale Mail",
      "Lattice Armor",
   ],
   "wood-structure": [
      "hellknight-plate",
      "Gray Maiden Plate",
      "Bastion Plate",
      "Fortress Plate",
      "full-plate",
      "half-plate",
      "splint-mail",
      "hellknight-half-plate",
   ],
}

export const baseWeaponMaterials = {
   glass: ["Alchemical Bomb"],
   "leather-thin": [
      "whip",
      "scorpion-whip",
      "Stiletto Pen",
      "Bladed Scarf",
      "Fighting Fan",
      "Monkey's Fist",
      "Rope Dart",
      "Sap",
      "Scourge",
      "Thorn Whip",
      "Umbrella Injector",
      "Whip Claw",
      "Bola",
      "Dart Umbrella",
   ],
   "wood-thin": [
      "Boomerang",
      "club",
      "shortbow",
      "longbow",
      "crossbow",
      "hand-crossbow",
      "blowgun",
      "sling",
      "javelin",
      "spear",
      "battle-lute",
      "Fighting Oar",
      "Forked Bipod",
      "Juggling Club",
      "Shears",
      "Combat Lure",
      "Cruuk",
      "Fighting Stick",
      "Fishing Lure",
      "Gaff",
      "Gill Hook",
      "Polytool",
      "Probing Cane",
      "Scythe",
      "Alchemical Crossbow",
      "Atlatl",
      "Dart",
      "Backpack Ballista",
      "Composite Longbow",
      "Composite Shortbow",
      "Gakgung",
      "Gauntlet Bow",
      "Halfling Sling Staff",
      "Kestros",
      "Rotary Bow",
      "Spraysling",
      "Sukgung",
      "Sun Sling",
      "Thunder Sling",
      "Wrist Launcher",
      "Daikyu",
      "Repeating Crossbow",
      "Repeating Hand Crossbow",
   ],
   leather: [
      "Poi",
      "Wheel Spikes",
      "Exquisite Sword Cane Sheath",
      "Wakizashi",
      "heavy-crossbow",
      "Repeating Heavy Crossbow",
      "Shield Bow",
      "Backpack Catapult",
      "Taw Launcher",
   ],
   wood: [
      "Ranseur",
      "Bow Staff",
      "staff",
      "bo-staff",
      "longspear",
      "Bec de Corbin",
      "Breaching Pike",
      "Boarding Pike",
      "Combat Fishing Pole",
      "Dancer's Spear",
      "Dueling Spear",
      "Fauchard",
      "Greatclub",
      "Griffon Cane",
      "halberd",
      "glaive",
      "guisarme",
      "Horsechopper",
      "Injection Spear",
      "Katana",
      "Khakkhara",
      "Leiomano",
      "Machete",
      "Macuahuitl",
      "Naginata",
      "Shield Spikes",
      "Shuan Ji",
      "Tetsubo",
      "Three Peaked Tree",
      "Tonfa",
      "Lance",
      "Whipstaff",
      "Aklys",
      "Bladed Diabolo",
      "Broadspear",
      "Capturing Spetum",
      "Gada",
      "Nodachi",
      "Arbalest",
      "Arquebus",
      "Chakri",
      "Shuriken",
      "Hongali Hornbow",
      "Phalanx Piercer",
   ],
   "iron-thin": [
      "Flingflenser",
      "Dwarven Scattergun",
      "Barricade Buster",
      "Spoon Gun",
      "Slide Pistol",
      "Shobhad Longrifle",
      "Pepperbox",
      "Jezail",
      "Harpoon",
      "Harmona Gun",
      "Dueling Pistol",
      "Dragon-Mouth Pistol",
      "Double-Barreled Pistol",
      "Double-barreled Musket",
      "Dawnsilver Tree",
      "Clan Pistol",
      "Blunderbuss",
      "Big Boom Gun",
      "Axe Musket",
      "Shield Pistol",
      "Long Air Repeater",
      "Hand Cannon",
      "Flintlock Pistol",
      "Flintlock Musket",
      "Fire Lance",
      "Coat Pistol",
      "Air Repeater",
      "Zulfikar",
      "Wrecker",
      "Visap",
      "Tricky Pick",
      "Three-Section Naginata",
      "Tamchal Chakram",
      "Chakram",
      "Switchscythe",
      "Spirit Thresher",
      "Spiral Rapier",
      "Sickle-Saber",
      "Shauth Lash",
      "Sawtooth Saber",
      "Rhoka Sword",
      "Orc Necksplitter",
      "Maul-Spade",
      "Karambit",
      "Kalis",
      "Hook Sword",
      "Gnome Flickmace",
      "Flying Talon",
      "Fire Poi",
      "Feng Huo Lun",
      "Falcata",
      "Explosive Dogslicer",
      "Dwarven Waraxe",
      "Dwarven Dorn-Dergar",
      "Donchak",
      "Clockwork Macuahuitl",
      "Chain Sword",
      "Butterfly Sword",
      "Butchering Axe",
      "Bladesweeper",
      "Bladed Hoop",
      "Aldori Dueling Sword",
      "Zhuazhi Bang",
      "Wish Knife",
      "Wish Blade",
      "War Razor",
      "War Lance",
      "War Javelin",
      "War Flail",
      "Urumi",
      "Triggerbrand",
      "Trident",
      "Tengu Gale Blade",
      "Temple Sword",
      "Tekko-Kagi",
      "Talwar",
      "Sword Cane",
      "Spiked Chain",
      "Shield Boss",
      "Shauth Blade",
      "Scizore",
      "Scimitar",
      "Sansetsukon",
      "Sai",
      "Reinforced Stock",
      "Rapier Pistol",
      "Piranha Kiss",
      "Piercing Wind",
      "Pick",
      "Pantograph Gauntlet",
      "Panabas",
      "Orc Skewermaul",
      "Orc Knuckle Dagger",
      "Ogre Hook",
      "Nunchaku",
      "Mikazuki",
      "Meteor Hammer",
      "Maul",
      "Mambele",
      "Main-gauche",
      "Mace Multipistol",
      "Long Hammer",
      "Liuyedao",
      "Lion Scythe",
      "Light Pick",
      "Light Hammer",
      "Lancer",
      "Kusarigama",
      "Kris",
      "Khopesh",
      "Kama",
      "Jiu Huan Dao",
      "Hatchet",
      "Hand Adze",
      "Hammer Gun",
      "Gun Sword",
      "Greatpick",
      "Gnome Hooked Hammer",
      "Gnome Amalgam Musket",
      "Gladius",
      "Flyssa",
      "Flail",
      "Filcher's Fork",
      "Fangwire",
      "Falchion",
      "Exquisite Sword Cane",
      "Elven Curve Blade",
      "Elven Branched Spear",
      "Earthbreaker",
      "Dogslicer",
      "Dandpatta",
      "Dagger Pistol",
      "Crescent Cross",
      "Combat Grapnel",
      "Claw Blade",
      "Cane Pistol",
      "Buugeng",
      "dagger",
      "rapier",
      "longsword",
      "shortsword",
      "bastard-sword",
      "greatsword",
      "battle-axe",
      "greataxe",
      "hatchet",
      "mace",
      "morningstar",
      "warhammer",
      "scythe",
      "katar",
      "kukri",
      "starknife",
      "Corset Knife",
      "Frying Pan",
      "Gauntlet",
      "Knuckle Duster",
      "Light Mace",
      "Nightstick",
      "Palstave",
      "Reinforced Frame",
      "Sickle",
      "Spiked Gauntlet",
      "Throwing Knife",
      "Thundermace",
      "Tri-Bladed Katar",
      "War Gavel",
      "Wheel Blades",
      "Adze",
      "Asp Coil",
      "Axe Musket",
      "Battle Saddle",
      "Bayonet",
      "Black Powder Knuckle Dusters",
      "Bladed Gauntlet",
      "Boarding Axe",
   ],
}

export const preciousMaterials = {
   dreamweb: {
      armor: { standard: { hd: 6, hp: 32 }, high: { hd: 9, hp: 44 } },
   },
   dragonhide: {
      armor: { standard: { hd: 7, hp: 28 }, high: { hd: 11, hp: 44 } },
   },
   "grisantian-pelt": {
      armor: { standard: { hd: 9, hp: 36 }, high: { hd: 11, hp: 44 } },
   },
   peachwood: {
      weapon: { standard: { hd: 4, hp: 16 }, high: { hd: 8, hp: 32 } },
   },
   warpglass: { weapon: { high: { hd: 8, hp: 32 } } },
   "sovereign-steel": {
      weapon: { standard: { hd: 7, hp: 28 }, high: { hd: 10, hp: 40 } },
      armor: { standard: { hd: 11, hp: 44 }, high: { hd: 14, hp: 56 } },
   },
   inubrix: {
      weapon: { standard: { hd: 4, hp: 16 }, high: { hd: 7, hp: 28 } },
      armor: { standard: { hd: 8, hp: 32 }, high: { hd: 11, hp: 44 } },
   },
   "keep-stone": {
      weapon: { high: { hd: 10, hp: 46 } },
      armor: { high: { hd: 14, hp: 60 } },
   },
   noqual: {
      weapon: { standard: { hd: 6, hp: 24 }, high: { hd: 10, hp: 40 } },
      armor: { standard: { hd: 10, hp: 40 }, high: { hd: 13, hp: 52 } },
   },
   orichalcum: {
      weapon: { high: { hd: 16, hp: 64 } },
      armor: { high: { hd: 18, hp: 72 } },
   },
   siccatite: {
      weapon: { standard: { hd: 6, hp: 24 }, high: { hd: 10, hp: 40 } },
      armor: { standard: { hd: 10, hp: 40 }, high: { hd: 13, hp: 52 } },
   },
   silver: {
      weapon: {
         low: { hd: 3, hp: 12 },
         standard: { hd: 5, hp: 20 },
         high: { hd: 8, hp: 32 },
      },
      armor: {
         low: { hd: 5, hp: 20 },
         standard: { hd: 7, hp: 28 },
         high: { hd: 10, hp: 40 },
      },
   },
   sisterstone: {
      weapon: {
         low: { hd: 6, hp: 18 },
         standard: { hd: 8, hp: 24 },
         high: { hd: 10, hp: 36 },
      },
      armor: {
         low: { hd: 10, hp: 28 },
         standard: { hd: 12, hp: 40 },
         high: { hd: 15, hp: 54 },
      },
   },
   djezet: {
      weapon: { standard: { hd: 5, hp: 20 }, high: { hd: 8, hp: 32 } },
      armor: { standard: { hd: 9, hp: 36 }, high: { hd: 12, hp: 48 } },
   },
   dawnsilver: {
      weapon: { standard: { hd: 5, hp: 20 }, high: { hd: 8, hp: 32 } },
      armor: { standard: { hd: 9, hp: 36 }, high: { hd: 12, hp: 48 } },
   },
   "cold-iron": {
      weapon: {
         low: { hd: 5, hp: 20 },
         standard: { hd: 7, hp: 28 },
         high: { hd: 10, hp: 40 },
      },
      armor: {
         low: { hd: 9, hp: 36 },
         standard: { hd: 11, hp: 44 },
         high: { hd: 14, hp: 56 },
      },
   },
   abysium: {
      weapon: { standard: { hd: 6, hp: 24 }, high: { hd: 10, hp: 40 } },
      armor: { standard: { hd: 10, hp: 40 }, high: { hd: 13, hp: 52 } },
   },
   adamantine: {
      weapon: { standard: { hd: 10, hp: 40 }, high: { hd: 13, hp: 52 } },
      armor: { standard: { hd: 14, hp: 56 }, high: { hd: 17, hp: 68 } },
   },
   duskwood: {
      weapon: { standard: { hd: 5, hp: 20 }, high: { hd: 8, hp: 32 } },
      armor: { standard: { hd: 7, hp: 28 }, high: { hd: 10, hp: 40 } },
   },
}
